import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO: SE INSTALO ESTAS 2 PARTES DE PRIMA: npm i prisma -D  Y  npm i @prisma/client
// TODO: COMO SEGUNDO PASO INICIALIZAMOS PRIMA npx prisma init --datasource-provider postgresql
//TODO: npx prisma migrate init --name init

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
